name: ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/ubuntu.yml'
      - '**.cpp'
      - '**.cpp'
      - '**.h'
      - '**.cmake'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - '.github/workflows/ubuntu.yml'
      - '**.cpp'
      - '**.cpp'
      - '**.h'
      - '**.cmake'
      - 'CMakeLists.txt'
jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
    # Dependencies
    - name: install dependencies for wxWidgets
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake libgtk-3-dev
    - name: install wxDatabase's dependencies
      run: sudo apt-get install unixodbc-dev odbc-postgresql libmariadb-dev libsqliteodbc freetds-dev

    # WxWidgets
    - name: Checkout WxWidgets
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        ref: v3.2.5
        submodules: recursive
        path: wxWidgets

    - name: build and install wxWidgets
      run: |
        mkdir -p wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --disable-debug_flag --with-gtk=3 --enable-stl
        make -j$(nproc) && sudo make install

    # wxDatabase
    - name: Checkout wxDatabase
      uses: actions/checkout@v4

    - name: build wxDatabase
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_MYSQL=1 -DENABLE_SQLITE=1 -DENABLE_PGS=1 -DENABLE_TDS=0 -DENABLE_ODBC=0 -DBUILD_SAMPLE=1
        cmake --build build -j $(nproc)
